import React, { useEffect, useRef } from "react";
import Hls from "hls.js";

interface VideoPlayerProps {
  title?: string;
}

const VideoPlayer: React.FC<VideoPlayerProps> = ({ title }) => {
  const videoRef = useRef<HTMLVideoElement | null>(null);

  useEffect(() => {
    if (!title || !videoRef.current) return;

    const video = videoRef.current;

    // Use LL-HLS master playlist generated by the backend.
    const masterUrl = `/hls/${title}/master.m3u8`;

    let hls: Hls | undefined;
    let cancelled = false;

    const selectSourceAndPlay = async () => {
      // Try master.m3u8 first; if it doesn't exist, use legacy index.m3u8.
      const exists = async (url: string) => {
        try {
          const res = await fetch(url, { method: "HEAD" });
          return res.ok;
        } catch {
          return false;
        }
      };

      const hasMaster = await exists(masterUrl);

      if (!hasMaster) {
        console.error("HLS master playlist not found:", masterUrl);
        return;
      }

      const src = masterUrl;

      if (cancelled) return;

      if (Hls.isSupported()) {
        hls = new Hls({
          lowLatencyMode: true,
        });
        hls.loadSource(src);
        hls.attachMedia(video);
      } else if (video.canPlayType("application/vnd.apple.mpegurl")) {
        video.src = src;
      }
    };

    selectSourceAndPlay();

    return () => {
      cancelled = true;
      if (hls) {
        hls.destroy();
      }
    };
  }, [title]);

  if (!title) {
    return (
      <div style={{ padding: 16 }}>
        <h2>Player</h2>
        <div>Select a video to start playback.</div>
      </div>
    );
  }

  return (
    <div style={{ padding: 16 }}>
      <h2>Now Playing: {title}</h2>
      <video
        ref={videoRef}
        controls
        style={{ width: "100%", maxHeight: 480, background: "#000" }}
      />
    </div>
  );
};

export default VideoPlayer;

